on: [push]

jobs:
  update_readme_job:
    runs-on: ubuntu-latest
    name: Update README
    steps:
    - name: Update README
      id: github-contentful-readme
      uses: Merlin04/github-contentful-readme@v0.0.12
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        headerKey: "github-header"
        subheaderKey: "github-subheader"
        footerKey: "github-footer"
        contentfulAccessToken: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
        contentfulSpaceId: ${{ secrets.CONTENTFUL_SPACE_ID }}
